#!c:\Documents\git\bitly\flask\Scripts\python.exe
# EASY-INSTALL-SCRIPT: 'sqlparse==0.1.14','sqlformat'
__requires__ = 'sqlparse==0.1.14'
__import__('pkg_resources').run_script('sqlparse==0.1.14', 'sqlformat')
